version: '3'
services:
  analyticsService:
    build: analyticsSVC
    networks:
      - gamePromo


  apiGateway:
    build: apiGateway
    networks:
      - gamePromo

  authService:
    build: authService
    networks:
      - gamePromo

  items_service:
    build:
      context: .
      dockerfile: itemsSvc/Dockerfile
    environment:
      DB_USER: ${ITEMS_SERVICE_DB_USER:-postgres}
      DB_PASSWORD: ${ITEMS_SERVICE_DB_PASSWORD:-postgres}
      DB_NAME: ${ITEMS_SERVICE_DB_NAME:-postgres}
      DB_HOST: ${ITEMS_SERVICE_DB_HOST:-items_service_db}
      DB_PORT: ${ITEMS_SERVICE_DB_PORT:-5432}
    depends_on:
      - items_service_db
    networks:
      - gamePromo

  items_service_db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${ITEMS_SERVICE_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${ITEMS_SERVICE_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${ITEMS_SERVICE_DB_NAME:-postgres}
    ports:
      - ${ITEMS_SERVICE_DB_PORT:-5432}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ITEMS_SERVICE_DB_USER:-postgres} -d ${ITEMS_SERVICE_DB_NAME:-postgres}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - items_service_db_data:/var/lib/postgresql/data
    networks:
      - gamePromo


  randomGeneratorService:
    build: randomGeneratorSVC
    networks:
      - gamePromo

  rewardDispatcher:
    build: rewardDispatcher
    networks:
      - gamePromo

  userProgressService:
    build: userProgressSVC
    networks:
      - gamePromo

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - gamePromo
    restart: always

volumes:
  items_service_db_data:

networks:
  gamePromo:
    driver: bridge