// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/items.proto

package GamePromo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Type          *string                `protobuf:"bytes,3,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Rarity        *string                `protobuf:"bytes,4,opt,name=rarity,proto3,oneof" json:"rarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_proto_items_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_items_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_items_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateItemRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateItemRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *UpdateItemRequest) GetRarity() string {
	if x != nil && x.Rarity != nil {
		return *x.Rarity
	}
	return ""
}

type UpdateItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []*UpdateItemRequest   `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemsRequest) Reset() {
	*x = UpdateItemsRequest{}
	mi := &file_proto_items_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemsRequest) ProtoMessage() {}

func (x *UpdateItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_items_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemsRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_items_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateItemsRequest) GetIds() []*UpdateItemRequest {
	if x != nil {
		return x.Ids
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Type          *ItemType              `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Rarity        *Rarity                `protobuf:"bytes,3,opt,name=rarity,proto3" json:"rarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_items_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_items_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_items_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetType() *ItemType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Item) GetRarity() *Rarity {
	if x != nil {
		return x.Rarity
	}
	return nil
}

type ItemType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemType) Reset() {
	*x = ItemType{}
	mi := &file_proto_items_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemType) ProtoMessage() {}

func (x *ItemType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_items_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemType.ProtoReflect.Descriptor instead.
func (*ItemType) Descriptor() ([]byte, []int) {
	return file_proto_items_proto_rawDescGZIP(), []int{3}
}

func (x *ItemType) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Rarity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Weight        float32                `protobuf:"fixed32,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Multiplier    float32                `protobuf:"fixed32,3,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rarity) Reset() {
	*x = Rarity{}
	mi := &file_proto_items_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rarity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rarity) ProtoMessage() {}

func (x *Rarity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_items_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rarity.ProtoReflect.Descriptor instead.
func (*Rarity) Descriptor() ([]byte, []int) {
	return file_proto_items_proto_rawDescGZIP(), []int{4}
}

func (x *Rarity) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Rarity) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Rarity) GetMultiplier() float32 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *Rarity) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type Items struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Items) Reset() {
	*x = Items{}
	mi := &file_proto_items_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Items) ProtoMessage() {}

func (x *Items) ProtoReflect() protoreflect.Message {
	mi := &file_proto_items_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Items.ProtoReflect.Descriptor instead.
func (*Items) Descriptor() ([]byte, []int) {
	return file_proto_items_proto_rawDescGZIP(), []int{5}
}

func (x *Items) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_items_proto protoreflect.FileDescriptor

const file_proto_items_proto_rawDesc = "" +
	"\n" +
	"\x11proto/items.proto\x12\tGamePromo\"\x92\x01\n" +
	"\x11UpdateItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x03 \x01(\tH\x01R\x04type\x88\x01\x01\x12\x1b\n" +
	"\x06rarity\x18\x04 \x01(\tH\x02R\x06rarity\x88\x01\x01B\b\n" +
	"\x06_titleB\a\n" +
	"\x05_typeB\t\n" +
	"\a_rarity\"D\n" +
	"\x12UpdateItemsRequest\x12.\n" +
	"\x03ids\x18\x01 \x03(\v2\x1c.GamePromo.UpdateItemRequestR\x03ids\"p\n" +
	"\x04Item\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12'\n" +
	"\x04type\x18\x02 \x01(\v2\x13.GamePromo.ItemTypeR\x04type\x12)\n" +
	"\x06rarity\x18\x03 \x01(\v2\x11.GamePromo.RarityR\x06rarity\" \n" +
	"\bItemType\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"l\n" +
	"\x06Rarity\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x02R\x06weight\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x03 \x01(\x02R\n" +
	"multiplier\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\".\n" +
	"\x05Items\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.GamePromo.ItemR\x05items2\xf6\x01\n" +
	"\fItemsService\x120\n" +
	"\n" +
	"CreateItem\x12\x0f.GamePromo.Item\x1a\x0f.GamePromo.Item\"\x00\x123\n" +
	"\vCreateItems\x12\x10.GamePromo.Items\x1a\x10.GamePromo.Items\"\x00\x12=\n" +
	"\n" +
	"UpdateItem\x12\x1c.GamePromo.UpdateItemRequest\x1a\x0f.GamePromo.Item\"\x00\x12@\n" +
	"\vUpdateItems\x12\x1d.GamePromo.UpdateItemsRequest\x1a\x10.GamePromo.Items\"\x00B&Z$github.com/AlekseiYuzhanin/GamePromob\x06proto3"

var (
	file_proto_items_proto_rawDescOnce sync.Once
	file_proto_items_proto_rawDescData []byte
)

func file_proto_items_proto_rawDescGZIP() []byte {
	file_proto_items_proto_rawDescOnce.Do(func() {
		file_proto_items_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_items_proto_rawDesc), len(file_proto_items_proto_rawDesc)))
	})
	return file_proto_items_proto_rawDescData
}

var file_proto_items_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_items_proto_goTypes = []any{
	(*UpdateItemRequest)(nil),  // 0: GamePromo.UpdateItemRequest
	(*UpdateItemsRequest)(nil), // 1: GamePromo.UpdateItemsRequest
	(*Item)(nil),               // 2: GamePromo.Item
	(*ItemType)(nil),           // 3: GamePromo.ItemType
	(*Rarity)(nil),             // 4: GamePromo.Rarity
	(*Items)(nil),              // 5: GamePromo.Items
}
var file_proto_items_proto_depIdxs = []int32{
	0, // 0: GamePromo.UpdateItemsRequest.ids:type_name -> GamePromo.UpdateItemRequest
	3, // 1: GamePromo.Item.type:type_name -> GamePromo.ItemType
	4, // 2: GamePromo.Item.rarity:type_name -> GamePromo.Rarity
	2, // 3: GamePromo.Items.items:type_name -> GamePromo.Item
	2, // 4: GamePromo.ItemsService.CreateItem:input_type -> GamePromo.Item
	5, // 5: GamePromo.ItemsService.CreateItems:input_type -> GamePromo.Items
	0, // 6: GamePromo.ItemsService.UpdateItem:input_type -> GamePromo.UpdateItemRequest
	1, // 7: GamePromo.ItemsService.UpdateItems:input_type -> GamePromo.UpdateItemsRequest
	2, // 8: GamePromo.ItemsService.CreateItem:output_type -> GamePromo.Item
	5, // 9: GamePromo.ItemsService.CreateItems:output_type -> GamePromo.Items
	2, // 10: GamePromo.ItemsService.UpdateItem:output_type -> GamePromo.Item
	5, // 11: GamePromo.ItemsService.UpdateItems:output_type -> GamePromo.Items
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_items_proto_init() }
func file_proto_items_proto_init() {
	if File_proto_items_proto != nil {
		return
	}
	file_proto_items_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_items_proto_rawDesc), len(file_proto_items_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_items_proto_goTypes,
		DependencyIndexes: file_proto_items_proto_depIdxs,
		MessageInfos:      file_proto_items_proto_msgTypes,
	}.Build()
	File_proto_items_proto = out.File
	file_proto_items_proto_goTypes = nil
	file_proto_items_proto_depIdxs = nil
}
